### ISSUE TITLE
Featurerequest for Gitlab-Support

### ISSUE THREAD

**Issue by Django-BOfH** [splitbrain/dokuwiki-plugin-gh#3]
HI Andy,

do you think it would be very costly to modify/optimize the plugin so that not only github but also any gitlab instance could be included.

Ex: `https://gitlab.nausch.org/django/example_13/-/raw/main/playbooks/admin_updates.yml`

Would be great if you could do something here. It should not be your loss - a bottle of fine Scottish whiskey would be sure for you! ;)

ttyl
Django

**Comment by splitbrain** [comment]
implemented.

**Comment by Django-BOfH** [comment]
Fantastic - you make me happy!
